// frontend/src/views/Positions.vue
<template>
  <div>
    <h1>Positions</h1>
    <b-list-group class="list">
      <b-list-group-item
        v-for="position in $store.state.positions"
        :key="position.id"
        >{{ position.primary_name }}
        <br />
        <span class="text-muted">{{
          position.secondary_name
        }}</span></b-list-group-item
      >
    </b-list-group>
  </div>
</template>

<script>
export default {
  components: {},
  data: function() {
    return {};
  },
};
</script>

<style scoped>
h1 {
  padding-top: 60px;
}
.list {
  padding-top: 80px;
}
</style>

// frontend/src/components/Positions.svelte
<script>
  import { client } from "../client.js";
  import { PositionsStore } from "../store.js";

  client.listPositions().then((positions) => {
    PositionsStore.update(() => {
      return positions;
    });
  });
</script>

<positions>
  <ul>
    {#each Object.entries($PositionsStore) as [id, position] (id)}
      <li>
        {position.primary_name} <span>{position.secondary_name}</span>
      </li>
    {/each}
  </ul>
</positions>

<style>
  ul {
    list-style-type: none;
    text-align: left;
  }
  li {
    margin-top: 0.5em;
    margin-bottom: 0.5em;
  }
  span {
    color: #6c757d;
    margin-left: 1em;
  }
</style>
